language: node_js
dist: trusty
sudo: required

branches:
  except:
    - /^v[0-9]/

node_js:
  - 4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - make test
